name: Translation Release

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run build script
      run: |
        python ./scripts/build_locale.py

    - name: Upload manual translation file
      uses: actions/upload-artifact@v1
      with:
        name: Manual translation
        path: output/ko.txt
    
    - name: Upload machine translation file
      uses: actions/upload-artifact@v1
      with:
        name: Machine translation
        path: output/ko_mt.txt
